### ISSUE TITLE
Usage documentation

### ISSUE THREAD

**Issue by klihelp** [derek1906/jFont-Checker#1]
The font-checking code usage need to be after the `<body>` tag or in js run the code in `window.onload()` or the jQuery version `$(document).ready()`.
Otherwise you get an `Uncaught TypeError: Cannot read property 'appendChild' of null`

**Comment by derek1906** [comment]
I made a small change so that it now appends to the root instead e7fc18075f8f060b8c0147d248b7fc61a8581bb3. This should fix the problem and it can start checking as soon as possible. Since `documentElement` doesn't work on IE I had to use `getElementsByTagName`.
