### ISSUE TITLE
Should add warning

### ISSUE THREAD

**Issue by JemarJones** [derek1906/jFont-Checker#2]
I just used this and ran into issues because i was running it in a script that had access other to a different DOM than the one i wanted to check the font on (The font was only actually available on that page). It might be useful to future devs if you added a little warning noting that this script does assume that it has access to the specific DOM that you're testing.

**Comment by derek1906** [comment]
The current code uses the DOM that it is included into. This can be overrode by changing the local `html` variable to the one you want.

**Comment by JemarJones** [comment]
In that case may i suggest adding a parameter to the API  to that effect? Makes it a bit easier than digginh through and figuring out how tha API works.

**Comment by derek1906** [comment]
Does this change 64b8283d87ae093ef71edc397b2d62f25238ade7 work in your case?

**Comment by JemarJones** [comment]
In my case trying to even get that document variable from the the html page that i want to use (so that i can even pass it as a parameter) actually turns out to be a bit of a pain that i can't figure out. I don't see why it wouldn't work though.

**Comment by derek1906** [comment]
Well the code needs a DOM reference to be passed in to know which to test on, so this is the best I could do.
