### ISSUE TITLE
Some questions about the code

### ISSUE THREAD

**Issue by lgati** [derek1906/jFont-Checker#4]
Hello Derek!

First of all, I would like to congrat you about the font checker code, I think it's exactly what I was looking for my webpages front end tests.

Secondly, I have some questions about the code and what's being checked in fact:

What's the idea of applying regex even I set the font parameter? For example, if I'm checking a font who has "-" and I set it on the function parameter, the character "-" will be removed and the function return will be false , correct?

The code checks if the font is being applied for an element definided here:

              document.getElementsByTagName("html")[0]

However it doesn't means that the font is being rendered on the browser, right?

For example, I have the element below and the font-family stack is "Arial, Times, Comic Suns":

                 <h1 class="headline">Text</h1>

I use the following expression to get the element:

                `document.querySelector('.headline)`

If I run checkfont() setting the parameter as 'Times', it will return true only if the font is loaded, but I can't precise if the current text is being rendered in the page.

Do you think that's possible to get the font-family which is being rendered for a specific element?

Thanks in advance!

**Comment by derek1906** [comment]
>If I'm checking a font who has "-" and I set it on the function parameter, the character "-" will be removed and the function return will be false

That is correct. Probably shouldn't include `\-` in the regex. The original idea of the regex is to remove certain characters that might create an invalid style property, but it's really not necessary if you are sure that the font name is valid.

>If I run checkfont() setting the parameter as 'Times', it will return true only if the font is loaded, but I can't precise if the current text is being rendered in the page.

`checkfont` checks whether a font is available on a system by creating two text containers and comparing their dimensions. For local fonts, the font should be applied by the browser (at least in browsers that I tested on) and `checkDimension()` should return the updated dimensions. For online fonts, `checkfont` is not going to wait for the font to load, but if you are loading an external font then you already the font "exists".

>Do you think that's possible to get the font-family which is being rendered for a specific element?

Figuring out the font being applied isn't one of the goals of `checkfont`, but the same principle can be applied by fetching a list of possible applied fonts (from the stylesheet) and checking them one by one.

**Comment by lgati** [comment]
Hi Derek!

Thanks for the answer. I'm closing this issue!
